default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: medach_development
  port: 5433

test:
  <<: *default
  database: medach_test

production:
  host: "ec2-54-235-65-224.compute-1.amazonaws.com"
  adapter: postgresql
  encoding: unicode
  database: "da485eahkif3h2"
  username: "nbezebhvydeyna"
  port: 5432
  password: "15026a7b7ccf0d828b7ca69cf7ea70c0bb754e0f8f8981b91001c085e378926f"

